"""esquema inicial: menú, clientes/conversaciones y pedidos (sección 8 de PLANEACION.md)

Revision ID: 0001
Revises:
Create Date: 2026-10-02 14:26:53.371121

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categoria")),
        sa.UniqueConstraint("codigo", name=op.f("uq_categoria_codigo")),
    )
    op.create_table(
        "cliente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telefono", sa.String(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=True),
        sa.Column("ultima_direccion", sa.String(), nullable=True),
        sa.Column("acepto_datos_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cliente")),
        sa.UniqueConstraint("telefono", name=op.f("uq_cliente_telefono")),
    )
    op.create_table(
        "grupo_opcion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "sabor",
                "salsa",
                "topping",
                "fruta",
                "variante",
                name="tipogrupo",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grupo_opcion")),
        sa.UniqueConstraint("codigo", name=op.f("uq_grupo_opcion_codigo")),
    )
    op.create_table(
        "medio_pago",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("numero_cuenta", sa.String(), nullable=True),
        sa.Column("titular", sa.String(), nullable=True),
        sa.Column("requiere_comprobante", sa.Boolean(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medio_pago")),
        sa.UniqueConstraint("codigo", name=op.f("uq_medio_pago_codigo")),
    )
    op.create_table(
        "negocio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("moneda", sa.String(), nullable=False),
        sa.Column("ciudad", sa.String(), nullable=False),
        sa.Column("horario", sa.String(), nullable=False),
        sa.Column("costo_domicilio", sa.Integer(), nullable=False),
        sa.Column("nota_domicilio", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_negocio")),
    )
    op.create_table(
        "adicional",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("precio", sa.Integer(), nullable=False),
        sa.Column("grupo_id", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.CheckConstraint("precio > 0", name=op.f("ck_adicional_precio_positivo")),
        sa.ForeignKeyConstraint(
            ["grupo_id"], ["grupo_opcion.id"], name=op.f("fk_adicional_grupo_id_grupo_opcion")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adicional")),
        sa.UniqueConstraint("codigo", name=op.f("uq_adicional_codigo")),
    )
    op.create_table(
        "conversacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column(
            "canal",
            sa.Enum("whatsapp", "web", name="canal", native_enum=False, length=30),
            nullable=False,
        ),
        sa.Column("id_externo", sa.String(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "INICIO",
                "SALUDO",
                "TOMANDO_PEDIDO",
                "COMPLETANDO_OPCIONES",
                "RESUMEN",
                "DATOS_ENTREGA",
                "ESPERANDO_PAGO",
                "PEDIDO_CONFIRMADO",
                "FIN",
                "CANCELADA",
                name="estadoconversacion",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "modo",
            sa.Enum("bot", "humano", name="modoconversacion", native_enum=False, length=30),
            nullable=False,
        ),
        sa.Column("contexto_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_conversacion_cliente_id_cliente")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversacion")),
        sa.UniqueConstraint("canal", "id_externo", name=op.f("uq_conversacion_canal_id_externo")),
    )
    op.create_index(
        op.f("ix_conversacion_cliente_id"), "conversacion", ["cliente_id"], unique=False
    )
    op.create_table(
        "opcion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grupo_id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("disponible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grupo_id"],
            ["grupo_opcion.id"],
            name=op.f("fk_opcion_grupo_id_grupo_opcion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opcion")),
        sa.UniqueConstraint("grupo_id", "codigo", name=op.f("uq_opcion_grupo_id_codigo")),
    )
    op.create_table(
        "producto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("precio", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.CheckConstraint("precio > 0", name=op.f("ck_producto_precio_positivo")),
        sa.ForeignKeyConstraint(
            ["categoria_id"], ["categoria.id"], name=op.f("fk_producto_categoria_id_categoria")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_producto")),
        sa.UniqueConstraint("codigo", name=op.f("uq_producto_codigo")),
    )
    op.create_index(op.f("ix_producto_categoria_id"), "producto", ["categoria_id"], unique=False)
    op.create_table(
        "mensaje",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversacion_id", sa.Integer(), nullable=False),
        sa.Column(
            "origen",
            sa.Enum("cliente", "bot", "humano", name="origenmensaje", native_enum=False, length=30),
            nullable=False,
        ),
        sa.Column("texto", sa.String(), nullable=True),
        sa.Column("media_url", sa.String(), nullable=True),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversacion_id"],
            ["conversacion.id"],
            name=op.f("fk_mensaje_conversacion_id_conversacion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mensaje")),
    )
    op.create_index(
        op.f("ix_mensaje_conversacion_id"), "mensaje", ["conversacion_id"], unique=False
    )
    op.create_table(
        "pedido",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("conversacion_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "BORRADOR",
                "PENDIENTE_PAGO",
                "PAGO_VERIFICADO",
                "EN_PREPARACION",
                "ENVIADO",
                "ENTREGADO",
                "CANCELADO",
                name="estadopedido",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "tipo_entrega",
            sa.Enum("domicilio", "recoger", name="tipoentrega", native_enum=False, length=30),
            nullable=False,
        ),
        sa.Column("subtotal", sa.Integer(), nullable=False),
        sa.Column("domicilio", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("direccion", sa.String(), nullable=True),
        sa.Column("medio_pago_id", sa.Integer(), nullable=True),
        sa.Column("comprobante_url", sa.String(), nullable=True),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND domicilio >= 0", name=op.f("ck_pedido_montos_no_negativos")
        ),
        sa.CheckConstraint("total = subtotal + domicilio", name=op.f("ck_pedido_total_cuadra")),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_pedido_cliente_id_cliente")
        ),
        sa.ForeignKeyConstraint(
            ["conversacion_id"],
            ["conversacion.id"],
            name=op.f("fk_pedido_conversacion_id_conversacion"),
        ),
        sa.ForeignKeyConstraint(
            ["medio_pago_id"], ["medio_pago.id"], name=op.f("fk_pedido_medio_pago_id_medio_pago")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedido")),
    )
    op.create_index(op.f("ix_pedido_cliente_id"), "pedido", ["cliente_id"], unique=False)
    op.create_index(op.f("ix_pedido_conversacion_id"), "pedido", ["conversacion_id"], unique=False)
    op.create_index(op.f("ix_pedido_estado"), "pedido", ["estado"], unique=False)
    op.create_table(
        "producto_seleccion",
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("grupo_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("permite_repetir", sa.Boolean(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.CheckConstraint("cantidad > 0", name=op.f("ck_producto_seleccion_cantidad_positiva")),
        sa.ForeignKeyConstraint(
            ["grupo_id"],
            ["grupo_opcion.id"],
            name=op.f("fk_producto_seleccion_grupo_id_grupo_opcion"),
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["producto.id"],
            name=op.f("fk_producto_seleccion_producto_id_producto"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("producto_id", "grupo_id", name=op.f("pk_producto_seleccion")),
    )
    op.create_table(
        "item_pedido",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Integer(), nullable=False),
        sa.Column("notas", sa.String(), nullable=True),
        sa.CheckConstraint("cantidad > 0", name=op.f("ck_item_pedido_cantidad_positiva")),
        sa.CheckConstraint("precio_unitario > 0", name=op.f("ck_item_pedido_precio_positivo")),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedido.id"],
            name=op.f("fk_item_pedido_pedido_id_pedido"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"], ["producto.id"], name=op.f("fk_item_pedido_producto_id_producto")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_pedido")),
    )
    op.create_index(op.f("ix_item_pedido_pedido_id"), "item_pedido", ["pedido_id"], unique=False)
    op.create_table(
        "item_adicional",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("adicional_id", sa.Integer(), nullable=False),
        sa.Column("opcion_id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Integer(), nullable=False),
        sa.CheckConstraint("cantidad > 0", name=op.f("ck_item_adicional_cantidad_positiva")),
        sa.CheckConstraint("precio_unitario > 0", name=op.f("ck_item_adicional_precio_positivo")),
        sa.ForeignKeyConstraint(
            ["adicional_id"],
            ["adicional.id"],
            name=op.f("fk_item_adicional_adicional_id_adicional"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item_pedido.id"],
            name=op.f("fk_item_adicional_item_id_item_pedido"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opcion_id"], ["opcion.id"], name=op.f("fk_item_adicional_opcion_id_opcion")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_adicional")),
    )
    op.create_index(op.f("ix_item_adicional_item_id"), "item_adicional", ["item_id"], unique=False)
    op.create_table(
        "item_opcion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("opcion_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("posicion", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item_pedido.id"],
            name=op.f("fk_item_opcion_item_id_item_pedido"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opcion_id"], ["opcion.id"], name=op.f("fk_item_opcion_opcion_id_opcion")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_opcion")),
        sa.UniqueConstraint("item_id", "posicion", name=op.f("uq_item_opcion_item_id_posicion")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_opcion")
    op.drop_index(op.f("ix_item_adicional_item_id"), table_name="item_adicional")
    op.drop_table("item_adicional")
    op.drop_index(op.f("ix_item_pedido_pedido_id"), table_name="item_pedido")
    op.drop_table("item_pedido")
    op.drop_table("producto_seleccion")
    op.drop_index(op.f("ix_pedido_estado"), table_name="pedido")
    op.drop_index(op.f("ix_pedido_conversacion_id"), table_name="pedido")
    op.drop_index(op.f("ix_pedido_cliente_id"), table_name="pedido")
    op.drop_table("pedido")
    op.drop_index(op.f("ix_mensaje_conversacion_id"), table_name="mensaje")
    op.drop_table("mensaje")
    op.drop_index(op.f("ix_producto_categoria_id"), table_name="producto")
    op.drop_table("producto")
    op.drop_table("opcion")
    op.drop_index(op.f("ix_conversacion_cliente_id"), table_name="conversacion")
    op.drop_table("conversacion")
    op.drop_table("adicional")
    op.drop_table("negocio")
    op.drop_table("medio_pago")
    op.drop_table("grupo_opcion")
    op.drop_table("cliente")
    op.drop_table("categoria")
    # ### end Alembic commands ###
