"""version del menu y activo en catalogo

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 14:38:17.124785

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categoria",
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "grupo_opcion",
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "negocio", sa.Column("version_menu", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "opcion", sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opcion", "activo")
    op.drop_column("negocio", "version_menu")
    op.drop_column("grupo_opcion", "activo")
    op.drop_column("categoria", "activo")
    # ### end Alembic commands ###
