"""id externo del mensaje

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 18:01:20.901238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mensaje", sa.Column("id_externo", sa.String(), nullable=True))
    op.create_unique_constraint(op.f("uq_mensaje_id_externo"), "mensaje", ["id_externo"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_mensaje_id_externo"), "mensaje", type_="unique")
    op.drop_column("mensaje", "id_externo")
    # ### end Alembic commands ###
